### ISSUE TITLE
Sakura's Blog

### ISSUE THREAD

**Issue by cloudflaresni** [theme-shoka-x/awesome-shokaX#5]
### 网站内容描述

简单的个人博客，主要以记录自己的技术实践和思想想法为主

### 网站域名

https://misakamikoto.eu.org

### 注意事项

- [X] 我已确认以上事项

**Comment by zkz098** [comment]
您好，您的网站存在一些问题，在修复后我们将会将您的网站添加进我方在线预览。
- ![image](https://user-images.githubusercontent.com/92242020/234864213-90044247-6bb2-49d7-9f7c-7c6fb5e3bad9.png)
  您的hexo-shokax-create-time未填写参数，存在无法正常显示问题
- ![image](https://user-images.githubusercontent.com/92242020/234864412-88ec2b33-f1c8-4179-94d6-0523f4023cf8.png)
  您的busuanzi未设置参数，无法正常显示
- 您的网站仅有一篇文章，且内容加密，我们无法判断其是否符合我方对内容的要求

您在完成修复后可回复此评论以提醒我修复已完成

**Comment by zkz098** [comment]
相关说明您可以查看: [busuanzi文档](https://github.com/theme-shoka-x/awesome-shokaX/blob/main/extensions/busuanzi/README.md) 和 [create-time文档](https://github.com/theme-shoka-x/awesome-shokaX/blob/main/extensions/create-time/README.MD)

**Comment by cloudflaresni** [comment]
busuanzi需要稍微多等待一会才能加载出来，我这边清除几次缓存加载之后看着正常，文章我先暂时打开方便审核，然后我先把下面这个修了

**Comment by cloudflaresni** [comment]
已经都修好了，欢迎查看 :) :100:

**Comment by zkz098** [comment]
我这边无法打开此网站，根据itdog显示DNS无法解析:
![image](https://github.com/theme-shoka-x/awesome-shokaX/assets/92242020/008d5248-8034-4b5e-b030-c6bf34bb4d17)

**Comment by cloudflaresni** [comment]
实在是抱歉，最近更换了一下域名。新域名sakurame.eu.org

**Comment by zkz098** [comment]
网站访问异常，显示Invalid SSL certificate Error code 526
![image](https://github.com/theme-shoka-x/awesome-shokaX/assets/92242020/e2905612-795e-4d2e-87ab-a1ec5dd7eca1)

**Comment by zkz098** [comment]
已恢复正常
